# Ironic API endpoint URL
ironic_url: http://{{ ansible_default_ipv4.address }}:6385

# Optional path to a nodes json file in the format used by tripleo-quickstart
nodes_json:

# List of nodes to register with Ironic. The dict structure directly
# corresponds to what is accepted by the os_ironic module:
# http://docs.ansible.com/ansible/os_ironic_module.html
nodes:
  - name: testnode
    driver: pxe_ipmitool
    driver_info:
      power:
        ipmi_username: username
        ipmi_password: password
        ipmi_address: 127.0.0.1
        ipmi_port: 6234
    nics:
      - mac: aa:bb:cc:aa:bb:cc
    properties:
      cpus: 1
      cpu_arch: x86_64
      ram: 8192
      disk_size: 40
      capabilities: profile:baremetal,boot_option:local
